# Creation of data frame

In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Import Statsmodels
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller
from statsmodels.tools.eval_measures import rmse, aic

In [97]:
df = pd.read_excel('/content/foglio EU.xlsx')

In [98]:
df.rename(columns={'Unnamed: 0': 'time'}, inplace=True)
df = df.set_index('time')

In [ ]:
df

# Visualize the Time Series

In [ ]:
# Plot
fig, axes = plt.subplots(nrows=1, ncols=2, dpi=120, figsize=(10,6))
for i, ax in enumerate(axes.flatten()):
    data = df[df.columns[i]]
    ax.plot(data, color='red', linewidth=1)
    # Decorations
    ax.set_title(df.columns[i])
    ax.xaxis.set_ticks_position('none')
    ax.yaxis.set_ticks_position('none')
    ax.spines["top"].set_alpha(0)
    ax.tick_params(labelsize=6)

plt.tight_layout();

# ACF PACF 

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.graphics.tsaplots import plot_pacf

In [ ]:
# GAS EU

f, ax = plt.subplots(nrows=2, ncols=1)
plot_acf(df['gas_eu'],lags=12, ax=ax[0])
plot_pacf(df['gas_eu'],lags=12, ax=ax[1], method='ols')

ax[1].annotate('Strong correlation at lag = 1', xy=(1, 0.6),  xycoords='data',
            xytext=(0.17, 0.75), textcoords='axes fraction',
            arrowprops=dict(color='red', shrink=0.05, width=1))

plt.tight_layout()
plt.show()

In [ ]:
# HICP EU
f, ax = plt.subplots(nrows=2, ncols=1)
plot_acf(df['hicp_eu'],lags=12, ax=ax[0])
plot_pacf(df['hicp_eu'],lags=12, ax=ax[1], method='ols')

ax[1].annotate('Strong correlation at lag = 1', xy=(1, 0.6),  xycoords='data',
            xytext=(0.17, 0.75), textcoords='axes fraction',
            arrowprops=dict(color='red', shrink=0.05, width=1))

plt.tight_layout()
plt.show()

In [ ]:
# GAS FR

#f, ax = plt.subplots(nrows=2, ncols=1)
#plot_acf(df['gas_fr'],lags=12, ax=ax[0])
#plot_pacf(df['gas_fr'],lags=12, ax=ax[1], method='ols')

#ax[1].annotate('Strong correlation at lag = 1', xy=(1, 0.6),  xycoords='data',
 #           xytext=(0.17, 0.75), textcoords='axes fraction',
 #           arrowprops=dict(color='red', shrink=0.05, width=1))

#plt.tight_layout()
#plt.show()

In [102]:
# GAS IT

#f, ax = plt.subplots(nrows=2, ncols=1)
#plot_acf(df['gas_it'],lags=12, ax=ax[0])
#plot_pacf(df['gas_it'],lags=12, ax=ax[1], method='ols')

#ax[1].annotate('Strong correlation at lag = 1', xy=(1, 0.6),  xycoords='data',
 #           xytext=(0.17, 0.75), textcoords='axes fraction',
 #           arrowprops=dict(color='red', shrink=0.05, width=1))

#plt.tight_layout()
#plt.show()

In [ ]:
# HICP FR
#f, ax = plt.subplots(nrows=2, ncols=1)
#plot_acf(df['hicp_fr'],lags=12, ax=ax[0])
#plot_pacf(df['hicp_fr'],lags=12, ax=ax[1], method='ols')

#ax[1].annotate('Strong correlation at lag = 1', xy=(1, 0.6),  xycoords='data',
 #           xytext=(0.17, 0.75), textcoords='axes fraction',
 #           arrowprops=dict(color='red', shrink=0.05, width=1))

#plt.tight_layout()
#plt.show()

In [104]:
# HICP IT
#f, ax = plt.subplots(nrows=2, ncols=1)
#plot_acf(df['hicp_it'],lags=12, ax=ax[0])
#plot_pacf(df['hicp_it'],lags=12, ax=ax[1], method='ols')

#ax[1].annotate('Strong correlation at lag = 1', xy=(1, 0.6),  xycoords='data',
 #           xytext=(0.17, 0.75), textcoords='axes fraction',
 #           arrowprops=dict(color='red', shrink=0.05, width=1))

#plt.tight_layout()
#plt.show()

In [ ]:


df = pd.DataFrame(np.random.standard_normal((300,3)))
model = VAR(df)
results = model.fit()
irf = results.irf(10)
print(irf.irfs)
print(irf.cum_effects)


[[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

 [[ 1.56315281e-02 -2.30654013e-02  1.20385981e-02]
  [ 2.49996973e-02 -1.17668949e-03  6.06904241e-04]
  [-4.91619673e-02 -1.41014635e-02 -3.30170442e-02]]

 [[-9.24124546e-04 -5.03168506e-04 -2.23295731e-04]
  [ 3.31529984e-04 -5.83801690e-04  2.80208987e-04]
  [ 5.02173852e-04  1.61612219e-03  4.89725799e-04]]

 [[-1.60468817e-05  2.50561732e-05 -4.05797414e-06]
  [-2.31881703e-05 -1.09112756e-05 -5.61482798e-06]
  [ 2.41764265e-05 -2.03903659e-05 -9.14299773e-06]]

 [[ 5.75057453e-07  3.97867805e-07 -4.39929518e-08]
  [-3.59209134e-07  6.26860928e-07 -1.00390140e-07]
  [ 3.17649271e-07 -4.04716201e-07  5.80550043e-07]]

 [[ 2.10983815e-08 -1.31117328e-08  8.61687047e-09]
  [ 1.49917225e-08  8.96333004e-09 -6.29344171e-10]
  [-3.36934212e-08 -1.50370878e-08 -1.55896185e-08]]

 [[-4.21611710e-10 -5.92724682e-10 -3.84662228e-11]


# Testing Causation using Granger’s Causality Test

In [ ]:
from statsmodels.tsa.stattools import grangercausalitytests
maxlag=12
test = 'ssr_chi2test'
def grangers_causation_matrix(data, variables, test='ssr_chi2test', verbose=False):    
    """Check Granger Causality of all possible combinations of the Time series.
    The rows are the response variable, columns are predictors. The values in the table 
    are the P-Values. P-Values lesser than the significance level (0.05), implies 
    the Null Hypothesis that the coefficients of the corresponding past values is 
    zero, that is, the X does not cause Y can be rejected.

    data      : pandas dataframe containing the time series variables
    variables : list containing names of the time series variables.
    """
    df = pd.DataFrame(np.zeros((len(variables), len(variables))), columns=variables, index=variables)
    for c in df.columns:
        for r in df.index:
            test_result = grangercausalitytests(data[[r, c]], maxlag=maxlag, verbose=False)
            p_values = [round(test_result[i+1][0][test][1],4) for i in range(maxlag)]
            if verbose: print(f'Y = {r}, X = {c}, P Values = {p_values}')
            min_p_value = np.min(p_values)
            df.loc[r, c] = min_p_value
    df.columns = [var + '_x' for var in variables]
    df.index = [var + '_y' for var in variables]
    return df

grangers_causation_matrix(df, variables = df.columns)

# Cointegration Test

In [ ]:
from statsmodels.tsa.vector_ar.vecm import coint_johansen

def cointegration_test(df, alpha=0.05): 
    """Perform Johanson's Cointegration Test and Report Summary"""
    out = coint_johansen(df,-1,5)
    d = {'0.90':0, '0.95':1, '0.99':2}
    traces = out.lr1
    cvts = out.cvt[:, d[str(1-alpha)]]
    def adjust(val, length= 6): return str(val).ljust(length)

    # Summary
    print('Name   ::  Test Stat > C(95%)    =>   Signif  \n', '--'*20)
    for col, trace, cvt in zip(df.columns, traces, cvts):
        print(adjust(col), ':: ', adjust(round(trace,2), 9), ">", adjust(cvt, 8), ' =>  ' , trace > cvt)

cointegration_test(df)

# Split the Series into Training and Testing Data

In [ ]:
df_train, df_test = df[0:-1], df[-1:]

# Check size
print(df_train.shape)
print(df_test.shape)  

#Check for Stationarity and Make the Time Series Stationary


In [109]:
def adfuller_test(series, signif=0.05, name='', verbose=False):
    """Perform ADFuller to test for Stationarity of given series and print report"""
    r = adfuller(series, autolag='AIC')
    output = {'test_statistic':round(r[0], 4), 'pvalue':round(r[1], 4), 'n_lags':round(r[2], 4), 'n_obs':r[3]}
    p_value = output['pvalue'] 
    def adjust(val, length= 6): return str(val).ljust(length)

    # Print Summary
    print(f'    Augmented Dickey-Fuller Test on "{name}"', "\n   ", '-'*47)
    print(f' Null Hypothesis: Data has unit root. Non-Stationary.')
    print(f' Significance Level    = {signif}')
    print(f' Test Statistic        = {output["test_statistic"]}')
    print(f' No. Lags Chosen       = {output["n_lags"]}')

    for key,val in r[4].items():
        print(f' Critical value {adjust(key)} = {round(val, 3)}')

    if p_value <= signif:
        print(f" => P-Value = {p_value}. Rejecting Null Hypothesis.")
        print(f" => Series is Stationary.")
    else:
        print(f" => P-Value = {p_value}. Weak evidence to reject the Null Hypothesis.")
        print(f" => Series is Non-Stationary.")   

In [ ]:
for name, column in df_train.iteritems():
    adfuller_test(column, name=column.name)
    print('\n')

##1st difference

In [111]:
df_differenced = df_train.diff().dropna()

In [ ]:
for name, column in df_differenced.iteritems():
    adfuller_test(column, name=column.name)
    print('\n')

## 2nd Difference


In [ ]:
# Second Differencing
#df_differenced = df_differenced.diff().dropna()
# ADF Test on each column of 2nd Differences Dataframe
#for name, column in df_differenced.iteritems():
 #   adfuller_test(column, name=column.name)
 #   print('\n')

#Select the Order (P) of VAR model

In [ ]:
model = VAR(df_differenced)
for i in [1,2,3,4,5,6,7,8,9]:
    result = model.fit(i)
    print('Lag Order =', i)
    print('AIC : ', result.aic)
    print('BIC : ', result.bic, '\n')

#Train the VAR Model of Selected Order(p)

In [ ]:
model_fitted = model.fit(3)
model_fitted.summary()

#Check for Serial Correlation of Residuals (Errors) using Durbin Watson Statistic

In [115]:
def adjust(val, length= 10): return str(val).ljust(length)

In [ ]:
from statsmodels.stats.stattools import durbin_watson
out = durbin_watson(model_fitted.resid)

for col, val in zip(df.columns, out):
    print(adjust(col), ':', round(val, 2))

#Forecast VAR model using statsmodels

In [ ]:
# Get the lag order
lag_order = model_fitted.k_ar
print(lag_order) 

# Input data for forecasting
forecast_input = df_differenced.values[-lag_order:]
forecast_input


In [ ]:
fc = model_fitted.forecast(y=forecast_input, steps=1)
df_forecast = pd.DataFrame(fc, index=df.index[-1:], columns=df.columns + '_2d')
df_forecast

#Invert the transformation to get the real forecast

In [119]:
def invert_transformation(df_train, df_forecast, second_diff=False):
    """Revert back the differencing to get the forecast to original scale."""
    df_fc = df_forecast.copy()
    columns = df_train.columns
    for col in columns:        
        # Roll back 2nd Diff
        if second_diff:
            df_fc[str(col)+'_1d'] = (df_train[col].iloc[-1]-df_train[col].iloc[-2]) + df_fc[str(col)+'_2d'].cumsum()
        # Roll back 1st Diff
        df_fc[str(col)+'_forecast'] = df_train[col].iloc[-1] + df_fc[str(col)+'_1d'].cumsum()
    return df_fc

In [120]:
df_results = invert_transformation(df_train, df_forecast, second_diff=True)        

In [ ]:
df_results

In [ ]:
df_results.loc[:, ['gas_eu_forecast','hicp_eu_forecast']]